stages:
  data_ingestion:
    cmd: python -m src.stages.data_ingestion_stage
    deps:
      - src/stages/data_ingestion_stage.py
      - src/components/data_ingestion.py
      - config/config.yaml
    outs:
      - data/raw

  data_transformation:
    cmd: python -m src.stages.data_transformation_stage
    deps:
      - src/stages/data_transformation_stage.py
      - src/components/data_transformation.py
      - data/raw
      - config/config.yaml
    outs:
      - data/preprocessed
      - artifacts/preprocessors/preprocessor.pkl

# Run pipeline to generate/update the dvc.lock file
# dvc repro