# ----------DATA INGESTION------------

data_ingestion:
  data_download_dir: data/raw
  dataset_name: "shivamb/machine-predictive-maintenance-classification"
  

# ----------DATA VALIDATION------------

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  data_file_path: data/raw/predictive_maintenance.csv